language: java

jdk:
  - openjdk11

script:
  - mvn clean package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "korthout-github"

after_success:
  - bash <(curl -s https://codecov.io/bash)